name: workloads
on:
  workflow_dispatch:  # manual
  pull_request:
    branches:
    - main
permissions: write-all

jobs:
  workloads:
    runs-on: ubuntu-20.04
    steps:

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::697830344472:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      # Set up dependencies
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: python3 -m pip install requirements.txt

      # Run workloads
      - name: Workloads
        run: |
          sh deploy/jobs/workloads.sh
      # Read results from S3
      - name: Read results from S3
        run: |
          aws s3 cp s3://madewml/${{ github.actor }}/results/ results/ --recursive
          python .github/workflows/json_to_md.py results/training_results.json results/training_results.md
          python .github/workflows/json_to_md.py results/evaluation_results.json results/evaluation_results.md

      # Comment results to PR
      - name: Comment training results on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: results/training_results.md
      - name: Comment evaluation results on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: results/evaluation_results.md
